# Generated by Django 5.2.8 on 2025-12-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='has_profanity',
            field=models.BooleanField(default=False),
        ),
    ]
