# Generated by Django 5.2.8 on 2025-12-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_comment_has_profanity'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profanity_severity',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
